### ISSUE TITLE
是否计划支持c#版本， 方便进行反射加载

### ISSUE THREAD

**Issue by M09Ic** [wgpsec/CreateHiddenAccount#4]
go编译后的大小有些不太方便， 如果有C#版本就更好了。

**Comment by teamssix** [comment]
目前没有这个计划，0x727 有一个 C++ 的，体积上要小很多，只是用起来需要注意用法，使用不当可能会造成机器无限重启，项目地址：https://github.com/0x727/CloneX_0x727
